baseurl: '/'
permalink: pretty
title: 'Datarix GmbH'
port: 4000
host: "0.0.0.0"

logo:
  mobile: "images/favicon-32x32.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo_website_arial.svg"
  desktop_height: "32px"
  desktop_width: "190px"

collections:
  services:
    output: true
  trainings:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "trainings"
    values:
      layout: "training"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
